#!/usr/bin/env python3
"""Generate the ZyPico logo assets from img/logo.png (run from the repo root):

    python3 tools/gen-logo.py

Outputs (committed, so normal builds/flashes need no Pillow):
  src/ui/pixel/logoBitmap.ts        128x80-fit PICO-8 indexed splash (255 = transparent)
  firmware/heltec-v3/src/logo_xbm.h 1-bit XBM for the Heltec OLED (u8g2 drawXBM)

The source is a glossy wordmark on an off-white background; we trim the margins,
fit each target, and quantize: the LCD to a curated PICO-8 ink subset over a
transparent (white) ground, the OLED to 1-bit ink.
"""
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "img", "logo.png")

# Curated PICO-8 ink colours (index -> rgb). White (7) is the splash ground, so
# near-white pixels become transparent rather than a flat white blob.
INK = {
    1: (0x1D, 0x2B, 0x53),   # dark-blue (letter edges)
    5: (0x5F, 0x57, 0x4F),   # dark-grey
    6: (0xC2, 0xC3, 0xC7),   # light-grey
    11: (0x00, 0xE4, 0x36),  # green (the dot on the i)
    12: (0x29, 0xAD, 0xFF),  # blue (letter fill)
}
TRANSPARENT = 255
LCD_W, LCD_H = 128, 80
OLED_W, OLED_H = 128, 64
INK_LUM_MAX = 210   # brighter than this on the LCD = gloss/background -> transparent
OLED_LUM_MAX = 200  # darker than this on the OLED = lit ink


def lum(r, g, b):
    return 0.299 * r + 0.587 * g + 0.114 * b


def trimmed():
    img = Image.open(SRC).convert("RGB")
    # Ink mask = anything clearly darker than the off-white ground.
    mask = img.convert("L").point(lambda v: 255 if v < 235 else 0)
    bbox = mask.getbbox()
    return img.crop(bbox) if bbox else img


def nearest_ink(r, g, b):
    best, bd = 1, 1e9
    for idx, (ir, ig, ib) in INK.items():
        d = (r - ir) ** 2 + (g - ig) ** 2 + (b - ib) ** 2
        if d < bd:
            bd, best = d, idx
    return best


def gen_lcd(crop):
    im = crop.copy()
    im.thumbnail((LCD_W, LCD_H), Image.LANCZOS)
    w, h = im.size
    px = im.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y][:3]
            out.append(TRANSPARENT if lum(r, g, b) > INK_LUM_MAX else nearest_ink(r, g, b))
    body = ",".join(str(v) for v in out)
    ts = (
        "// GENERATED by tools/gen-logo.py — do not edit. Regenerate: python3 tools/gen-logo.py\n"
        "// ZyPico wordmark, fit to the 128x80 matrix and quantized to a PICO-8 ink subset.\n"
        "// One byte per pixel = palette index, row-major; 255 = transparent (let the\n"
        "// splash background show through).\n\n"
        f"export const LOGO_W = {w};\n"
        f"export const LOGO_H = {h};\n"
        f"export const LOGO_TRANSPARENT = {TRANSPARENT};\n"
        f"export const LOGO: Uint8Array = new Uint8Array([{body}]);\n"
    )
    path = os.path.join(ROOT, "src", "ui", "pixel", "logoBitmap.ts")
    with open(path, "w") as f:
        f.write(ts)
    print(f"wrote {path}  ({w}x{h})")


def gen_oled(crop):
    im = crop.copy()
    im.thumbnail((OLED_W, OLED_H), Image.LANCZOS)
    w, h = im.size
    px = im.convert("L").load()
    bpr = (w + 7) // 8
    bits = bytearray(bpr * h)
    for y in range(h):
        for x in range(w):
            if px[x, y] < OLED_LUM_MAX:                 # ink -> lit
                bits[y * bpr + (x >> 3)] |= 1 << (x & 7)  # XBM: bit0 = leftmost
    rows = ",".join(f"0x{b:02x}" for b in bits)
    hdr = (
        "// GENERATED by tools/gen-logo.py — do not edit. Regenerate: python3 tools/gen-logo.py\n"
        "// ZyPico wordmark, 1-bit XBM for the Heltec OLED (u8g2 drawXBM, lit = ink).\n\n"
        "#pragma once\n"
        f"#define ZYPICO_LOGO_W {w}\n"
        f"#define ZYPICO_LOGO_H {h}\n"
        f"static const unsigned char ZYPICO_LOGO_BITS[] = {{{rows}}};\n"
    )
    path = os.path.join(ROOT, "firmware", "heltec-v3", "src", "logo_xbm.h")
    with open(path, "w") as f:
        f.write(hdr)
    print(f"wrote {path}  ({w}x{h}, {len(bits)} bytes)")


def main():
    crop = trimmed()
    print(f"trimmed wordmark: {crop.size[0]}x{crop.size[1]}")
    gen_lcd(crop)
    gen_oled(crop)


if __name__ == "__main__":
    main()
